#Mystvale Academy save file
#Fri May 15 16:45:32 PST 2026
hero.attack=1551
hero.baseAtk=550
hero.baseDef=180
hero.baseHp=4000
hero.baseMana=1000
hero.bonusAtk=127
hero.bonusDef=66
hero.bonusHp=254
hero.bonusMana=189
hero.canEnterArea1=true
hero.canEnterArea2=true
hero.canEnterArea3=true
hero.charClass=Mage
hero.cooldown1=0
hero.cooldown2=0
hero.cooldownU=0
hero.currentlyTraining=false
hero.defense=481
hero.experience=0
hero.finishedAllTraining=true
hero.finishedDurability=true
hero.finishedEndurance=true
hero.finishedManaRefinement=true
hero.finishedStrength=true
hero.gold=0
hero.gunnerCharacterChosen=false
hero.hasConversedWithShop=false
hero.hasOpenedInventory=false
hero.hasVisitedAcademy=true
hero.hasVisitedArea1=true
hero.hasVisitedArea2=true
hero.hasVisitedArea3=false
hero.hasVisitedBookFinding=false
hero.hasVisitedGym=true
hero.hasVisitedLibrary=true
hero.hasVisitedOffice=true
hero.hasVisitedPrologue=false
hero.hasVisitedRiddles=false
hero.hasVisitedShop=true
hero.haveAcceptedButExited=false
hero.haveDefeatedArea1Boss=true
hero.haveDefeatedArea2Boss=true
hero.haveDefeatedArea3Boss=false
hero.haveEntered=false
hero.haveExploredButExited=false
hero.hp=15114
hero.hpCap=15114
hero.level=41
hero.libraryQuest1Done=true
hero.libraryQuest2Done=true
hero.mageCharacterChosen=true
hero.mana=2094
hero.manaCap=2094
hero.manaCostSkill1=275
hero.manaCostSkill2=545
hero.manaCostUltimate=850
hero.maxAtk=2000
hero.maxDef=570
hero.maxHp=22000
hero.maxMana=2500
hero.name=Mleux, the Windwhisperer
hero.numberOfTrainingFinished=4
hero.poisoned=0
hero.riddle1Done=true
hero.riddle2Done=true
hero.riddle3Done=true
hero.skill1=Stellar Shard
hero.skill2=Chains of Starlight
hero.skillCd1=0
hero.skillCd2=0
hero.skillCdU=0
hero.speed=90
hero.stunned=-1
hero.swordmanCharacterChosen=false
hero.type=com.ror.models.Mage
hero.ultimate=Astral Cataclysm
hero.unlockedArea1=true
hero.unlockedArea2=true
hero.unlockedArea3=true
hero.weapon=Wooden Staff
inventory.capacity=99
inventory.largeHealthPotion=3
inventory.largeManaPotion=1
inventory.mediumHealthPotion=1
inventory.mediumManaPotion=0
inventory.smallHealthPotion=6
inventory.smallManaPotion=4
save.savedAt=2026-05-15T08\:45\:32.209613100Z
save.slot=3
save.version=1
