#Mystvale Academy save file
#Fri May 15 13:54:01 PST 2026
hero.attack=821
hero.baseAtk=535
hero.baseDef=125
hero.baseHp=4000
hero.baseMana=600
hero.bonusAtk=676767
hero.bonusDef=73
hero.bonusHp=293
hero.bonusMana=220
hero.canEnterArea1=true
hero.canEnterArea2=false
hero.canEnterArea3=false
hero.charClass=Gunner
hero.cooldown1=0
hero.cooldown2=0
hero.cooldownU=0
hero.currentlyTraining=false
hero.defense=286
hero.experience=0
hero.finishedAllTraining=true
hero.finishedDurability=true
hero.finishedEndurance=true
hero.finishedManaRefinement=true
hero.finishedStrength=true
hero.gold=7260
hero.gunnerCharacterChosen=true
hero.hasConversedWithShop=false
hero.hasOpenedInventory=false
hero.hasVisitedAcademy=true
hero.hasVisitedArea1=true
hero.hasVisitedArea2=false
hero.hasVisitedArea3=false
hero.hasVisitedBookFinding=false
hero.hasVisitedGym=true
hero.hasVisitedLibrary=true
hero.hasVisitedOffice=true
hero.hasVisitedPrologue=false
hero.hasVisitedRiddles=false
hero.hasVisitedShop=false
hero.haveAcceptedButExited=false
hero.haveDefeatedArea1Boss=false
hero.haveDefeatedArea2Boss=false
hero.haveDefeatedArea3Boss=false
hero.haveEntered=false
hero.haveExploredButExited=false
hero.hp=7327
hero.hpCap=7327
hero.level=16
hero.libraryQuest1Done=true
hero.libraryQuest2Done=false
hero.mageCharacterChosen=false
hero.mana=976
hero.manaCap=976
hero.manaCostSkill1=150
hero.manaCostSkill2=275
hero.manaCostUltimate=450
hero.maxAtk=1500
hero.maxDef=650
hero.maxHp=22000
hero.maxMana=1530
hero.name=Fehld, the Ashened
hero.numberOfTrainingFinished=4
hero.poisoned=0
hero.riddle1Done=false
hero.riddle2Done=true
hero.riddle3Done=true
hero.skill1=Crimson Barrage
hero.skill2=Frostwind Bullet
hero.skillCd1=0
hero.skillCd2=0
hero.skillCdU=0
hero.speed=150
hero.stunned=-1
hero.swordmanCharacterChosen=false
hero.type=com.ror.models.Gunner
hero.ultimate=Judgement Phantom
hero.unlockedArea1=true
hero.unlockedArea2=false
hero.unlockedArea3=false
hero.weapon=Marksman Rifle
inventory.capacity=99
inventory.largeHealthPotion=0
inventory.largeManaPotion=0
inventory.mediumHealthPotion=0
inventory.mediumManaPotion=0
inventory.smallHealthPotion=0
inventory.smallManaPotion=0
save.savedAt=2026-05-15T05\:54\:01.562043Z
save.slot=1
save.version=1
